services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile-ubuntu
    # command: zsh
    networks:
      - ctf
  alpine:
    build:
      context: .
      dockerfile: Dockerfile-alpine

networks:
  ctf:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"